"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[[completion.keymap]]
desc = "Cancel completion"
on = ["<C-q>"]
run = "close"

[[completion.keymap]]
desc = "Submit the completion"
on = ["<Tab>"]
run = "close --submit"

[[completion.keymap]]
desc = "Submit the completion and input"
on = ["<Enter>"]
run = ["close --submit", "close_input --submit"]

[[completion.keymap]]
desc = "Move cursor up"
on = ["<A-k>"]
run = "arrow -1"

[[completion.keymap]]
desc = "Move cursor down"
on = ["<A-j>"]
run = "arrow 1"

[[completion.keymap]]
desc = "Move cursor up"
on = ["<Up>"]
run = "arrow -1"

[[completion.keymap]]
desc = "Move cursor down"
on = ["<Down>"]
run = "arrow 1"

[[completion.keymap]]
desc = "Open help"
on = ["~"]
run = "help"

[[help.keymap]]
desc = "Clear the filter, or hide the help"
on = ["<Esc>"]
run = "escape"

[[help.keymap]]
desc = "Exit the process"
on = ["q"]
run = "close"

[[help.keymap]]
desc = "Hide the help"
on = ["<C-q>"]
run = "close"

[[help.keymap]]
desc = "Move cursor up"
on = ["k"]
run = "arrow -1"

[[help.keymap]]
desc = "Move cursor down"
on = ["j"]
run = "arrow 1"

[[help.keymap]]
desc = "Move cursor up 5 lines"
on = ["K"]
run = "arrow -5"

[[help.keymap]]
desc = "Move cursor down 5 lines"
on = ["J"]
run = "arrow 5"

[[help.keymap]]
desc = "Move cursor up"
on = ["<Up>"]
run = "arrow -1"

[[help.keymap]]
desc = "Move cursor down"
on = ["<Down>"]
run = "arrow 1"

[[help.keymap]]
desc = "Move cursor up 5 lines"
on = ["<S-Up>"]
run = "arrow -5"

[[help.keymap]]
desc = "Move cursor down 5 lines"
on = ["<S-Down>"]
run = "arrow 5"

[[help.keymap]]
desc = "Apply a filter for the help items"
on = ["/"]
run = "filter"

[[input.keymap]]
desc = "Cancel input"
on = ["<C-q>"]
run = "close"

[[input.keymap]]
desc = "Submit the input"
on = ["<Enter>"]
run = "close --submit"

[[input.keymap]]
desc = "Go back the normal mode, or cancel input"
on = ["<Esc>"]
run = "escape"

[[input.keymap]]
desc = "Enter insert mode"
on = ["i"]
run = "insert"

[[input.keymap]]
desc = "Enter append mode"
on = ["a"]
run = "insert --append"

[[input.keymap]]
desc = "Move to the BOL, and enter insert mode"
on = ["I"]
run = ["move -999", "insert"]

[[input.keymap]]
desc = "Move to the EOL, and enter append mode"
on = ["A"]
run = ["move 999", "insert --append"]

[[input.keymap]]
desc = "Enter visual mode"
on = ["v"]
run = "visual"

[[input.keymap]]
desc = "Enter visual mode and select all"
on = ["V"]
run = ["move -999", "visual", "move 999"]

[[input.keymap]]
desc = "Move back a character"
on = ["h"]
run = "move -1"

[[input.keymap]]
desc = "Move forward a character"
on = ["l"]
run = "move 1"

[[input.keymap]]
desc = "Move back a character"
on = ["<Left>"]
run = "move -1"

[[input.keymap]]
desc = "Move forward a character"
on = ["<Right>"]
run = "move 1"

[[input.keymap]]
desc = "Move back a character"
on = ["<C-b>"]
run = "move -1"

[[input.keymap]]
desc = "Move forward a character"
on = ["<C-f>"]
run = "move 1"

[[input.keymap]]
desc = "Move back to the start of the current or previous word"
on = ["b"]
run = "backward"

[[input.keymap]]
desc = "Move forward to the start of the next word"
on = ["w"]
run = "forward"

[[input.keymap]]
desc = "Move forward to the end of the current or next word"
on = ["e"]
run = "forward --end-of-word"

[[input.keymap]]
desc = "Move back to the start of the current or previous word"
on = ["<A-b>"]
run = "backward"

[[input.keymap]]
desc = "Move forward to the end of the current or next word"
on = ["<A-f>"]
run = "forward --end-of-word"

[[input.keymap]]
desc = "Move to the BOL"
on = ["0"]
run = "move -999"

[[input.keymap]]
desc = "Move to the EOL"
on = ["$"]
run = "move 999"

[[input.keymap]]
desc = "Move to the BOL"
on = ["<C-a>"]
run = "move -999"

[[input.keymap]]
desc = "Move to the EOL"
on = ["<C-e>"]
run = "move 999"

[[input.keymap]]
desc = "Delete the character before the cursor"
on = ["<Backspace>"]
run = "backspace"

[[input.keymap]]
desc = "Delete the character before the cursor"
on = ["<C-h>"]
run = "backspace"

[[input.keymap]]
desc = "Delete the character under the cursor"
on = ["<C-d>"]
run = "backspace --under"

[[input.keymap]]
desc = "Kill backwards to the BOL"
on = ["<C-u>"]
run = "kill bol"

[[input.keymap]]
desc = "Kill forwards to the EOL"
on = ["<C-k>"]
run = "kill eol"

[[input.keymap]]
desc = "Kill backwards to the start of the current word"
on = ["<C-w>"]
run = "kill backward"

[[input.keymap]]
desc = "Kill forwards to the end of the current word"
on = ["<A-d>"]
run = "kill forward"

[[input.keymap]]
desc = "Cut the selected characters"
on = ["d"]
run = "delete --cut"

[[input.keymap]]
desc = "Cut until the EOL"
on = ["D"]
run = ["delete --cut", "move 999"]

[[input.keymap]]
desc = "Cut the selected characters, and enter insert mode"
on = ["c"]
run = "delete --cut --insert"

[[input.keymap]]
desc = "Cut until the EOL, and enter insert mode"
on = ["C"]
run = ["delete --cut --insert", "move 999"]

[[input.keymap]]
desc = "Cut the current character"
on = ["x"]
run = ["delete --cut", "move 1 --in-operating"]

[[input.keymap]]
desc = "Copy the selected characters"
on = ["y"]
run = "yank"

[[input.keymap]]
desc = "Paste the copied characters after the cursor"
on = ["p"]
run = "paste"

[[input.keymap]]
desc = "Paste the copied characters before the cursor"
on = ["P"]
run = "paste --before"

[[input.keymap]]
desc = "Undo the last operation"
on = ["u"]
run = "undo"

[[input.keymap]]
desc = "Redo the last operation"
on = ["<C-r>"]
run = "redo"

[[input.keymap]]
desc = "Open help"
on = ["~"]
run = "help"

[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"

[[mgr.keymap]]
desc = "Exit visual mode, clear selected, or cancel search"
on = ["<Esc>"]
run = "escape"

[[mgr.keymap]]
desc = "Exit the process"
on = ["q"]
run = "quit"

[[mgr.keymap]]
desc = "Exit the process without writing cwd-file"
on = ["Q"]
run = "quit --no-cwd-file"

[[mgr.keymap]]
desc = "Close the current tab, or quit if it is last tab"
on = ["<C-q>"]
run = "close"

[[mgr.keymap]]
desc = "Suspend the process"
on = ["<C-z>"]
run = "suspend"

[[mgr.keymap]]
desc = "Move cursor up"
on = ["k"]
run = "arrow -1"

[[mgr.keymap]]
desc = "Move cursor down"
on = ["j"]
run = "arrow 1"

[[mgr.keymap]]
desc = "Move cursor up 5 lines"
on = ["K"]
run = "arrow -5"

[[mgr.keymap]]
desc = "Move cursor down 5 lines"
on = ["J"]
run = "arrow 5"

[[mgr.keymap]]
desc = "Move cursor up 5 lines"
on = ["<S-Up>"]
run = "arrow -5"

[[mgr.keymap]]
desc = "Move cursor down 5 lines"
on = ["<S-Down>"]
run = "arrow 5"

[[mgr.keymap]]
desc = "Move cursor up half page"
on = ["<C-u>"]
run = "arrow -50%"

[[mgr.keymap]]
desc = "Move cursor down half page"
on = ["<C-d>"]
run = "arrow 50%"

[[mgr.keymap]]
desc = "Move cursor up one page"
on = ["<C-b>"]
run = "arrow -100%"

[[mgr.keymap]]
desc = "Move cursor down one page"
on = ["<C-f>"]
run = "arrow 100%"

[[mgr.keymap]]
desc = "Move cursor up half page"
on = ["<C-PageUp>"]
run = "arrow -50%"

[[mgr.keymap]]
desc = "Move cursor down half page"
on = ["<C-PageDown>"]
run = "arrow 50%"

[[mgr.keymap]]
desc = "Move cursor up one page"
on = ["<PageUp>"]
run = "arrow -100%"

[[mgr.keymap]]
desc = "Move cursor down one page"
on = ["<PageDown>"]
run = "arrow 100%"

[[mgr.keymap]]
desc = "Go back to the parent directory"
on = ["h"]
run = ["leave", "escape --visual --select"]

[[mgr.keymap]]
desc = "Enter the child directory"
on = ["l"]
run = ["enter", "escape --visual --select"]

[[mgr.keymap]]
desc = "Go back to the previous directory"
on = ["H"]
run = "back"

[[mgr.keymap]]
desc = "Go forward to the next directory"
on = ["L"]
run = "forward"

[[mgr.keymap]]
desc = "Seek up 5 units in the preview"
on = ["<A-k>"]
run = "seek -5"

[[mgr.keymap]]
desc = "Seek down 5 units in the preview"
on = ["<A-j>"]
run = "seek 5"

[[mgr.keymap]]
desc = "Seek up 5 units in the preview"
on = ["<A-PageUp>"]
run = "seek -5"

[[mgr.keymap]]
desc = "Seek down 5 units in the preview"
on = ["<A-PageDown>"]
run = "seek 5"

[[mgr.keymap]]
desc = "Move cursor up"
on = ["<Up>"]
run = "arrow -1"

[[mgr.keymap]]
desc = "Move cursor down"
on = ["<Down>"]
run = "arrow 1"

[[mgr.keymap]]
desc = "Go back to the parent directory"
on = ["<Left>"]
run = "leave"

[[mgr.keymap]]
desc = "Enter the child directory"
on = ["<Right>"]
run = "enter"

[[mgr.keymap]]
desc = "Move cursor to the top"
on = ["g", "g"]
run = "arrow top"

[[mgr.keymap]]
desc = "Move cursor to the bottom"
on = ["G"]
run = "arrow bot"

[[mgr.keymap]]
desc = "Toggle the current selection state"
on = ["<Space>"]
run = ["select --state=none", "arrow 1"]

[[mgr.keymap]]
desc = "Enter visual mode (selection mode)"
on = ["v"]
run = "visual_mode"

[[mgr.keymap]]
desc = "Enter visual mode (unset mode)"
on = ["V"]
run = "visual_mode --unset"

[[mgr.keymap]]
desc = "Select all files"
on = ["<C-a>"]
run = "select_all --state=true"

[[mgr.keymap]]
desc = "Inverse selection of all files"
on = ["<C-r>"]
run = "select_all --state=none"

[[mgr.keymap]]
desc = "Open the selected files interactively"
on = ["o"]
run = "open --interactive"

[[mgr.keymap]]
desc = "Open the selected files interactively"
on = ["O"]
run = "open --interactive"

[[mgr.keymap]]
desc = "Enter the child directory, or open the file"
on = ["<Enter>"]
run = "plugin smart-enter"

[[mgr.keymap]]
desc = "Open the selected files interactively"
on = ["<C-Enter>"]
run = "open --interactive"

[[mgr.keymap]]
desc = "Copy the selected files"
on = ["y"]
run = ["yank", "escape --visual --select"]

[[mgr.keymap]]
desc = "Cut the selected files"
on = ["x"]
run = ["yank --cut", "escape --visual --select"]

[[mgr.keymap]]
desc = "Paste the files"
on = ["p"]
run = "paste"

[[mgr.keymap]]
desc = "Paste the files (overwrite if the destination exists)"
on = ["P"]
run = "paste --force"

[[mgr.keymap]]
desc = "Symlink the absolute path of files"
on = ["-"]
run = "link"

[[mgr.keymap]]
desc = "Symlink the relative path of files"
on = ["_"]
run = "link --relative"

[[mgr.keymap]]
desc = "Move the files to the trash"
on = ["d"]
run = ["remove", "escape --visual --select"]

[[mgr.keymap]]
desc = "Permanently delete the files"
on = ["D"]
run = ["remove --permanently", "escape --visual --select"]

[[mgr.keymap]]
desc = "Create a file or directory (ends with / for directories)"
on = ["a"]
run = "create"

[[mgr.keymap]]
desc = "Rename a file or directory"
on = ["r"]
run = "rename --cursor=before_ext"

[[mgr.keymap]]
desc = "Run a shell command"
on = [";"]
run = "shell --interactive"

[[mgr.keymap]]
desc = "Run a shell command (block the UI until the command finishes)"
on = [":"]
run = "shell --interactive"

[[mgr.keymap]]
desc = "Toggle the visibility of hidden files"
on = ["."]
run = "hidden toggle"

[[mgr.keymap]]
desc = "Search files by name using fd"
on = ["s"]
run = "search fd"

[[mgr.keymap]]
desc = "Search files by content using ripgrep"
on = ["S"]
run = "search rg"

[[mgr.keymap]]
desc = "Cancel the ongoing search"
on = ["<C-s>"]
run = "search none"

[[mgr.keymap]]
desc = "Jump to a directory using zoxide"
on = ["z"]
run = "jump zoxide"

[[mgr.keymap]]
desc = "Jump to a directory, or reveal a file using fzf"
on = ["Z"]
run = "jump fzf"

[[mgr.keymap]]
desc = "Set linemode to size"
on = ["m", "s"]
run = "linemode size"

[[mgr.keymap]]
desc = "Set linemode to permissions"
on = ["m", "p"]
run = "linemode permissions"

[[mgr.keymap]]
desc = "Set linemode to mtime"
on = ["m", "m"]
run = "linemode mtime"

[[mgr.keymap]]
desc = "Set linemode to none"
on = ["m", "n"]
run = "linemode none"

[[mgr.keymap]]
desc = "Copy the absolute path"
on = ["c", "c"]
run = "copy path"

[[mgr.keymap]]
desc = "Copy the path of the parent directory"
on = ["c", "d"]
run = "copy dirname"

[[mgr.keymap]]
desc = "Copy the name of the file"
on = ["c", "f"]
run = "copy filename"

[[mgr.keymap]]
desc = "Copy the name of the file without the extension"
on = ["c", "n"]
run = "copy name_without_ext"

[[mgr.keymap]]
desc = "Filter the files"
on = ["f"]
run = "filter --smart"

[[mgr.keymap]]
desc = "Find next file"
on = ["/"]
run = "find --smart"

[[mgr.keymap]]
desc = "Find previous file"
on = ["?"]
run = "find --previous --smart"

[[mgr.keymap]]
desc = "Go to next found file"
on = ["n"]
run = "find_arrow"

[[mgr.keymap]]
desc = "Go to previous found file"
on = ["N"]
run = "find_arrow --previous"

[[mgr.keymap]]
desc = "Sort by modified time"
on = [",", "m"]
run = "sort modified --dir-first"

[[mgr.keymap]]
desc = "Sort by modified time (reverse)"
on = [",", "M"]
run = "sort modified --reverse --dir-first"

[[mgr.keymap]]
desc = "Sort by created time"
on = [",", "c"]
run = "sort created --dir-first"

[[mgr.keymap]]
desc = "Sort by created time (reverse)"
on = [",", "C"]
run = "sort created --reverse --dir-first"

[[mgr.keymap]]
desc = "Sort by extension"
on = [",", "e"]
run = "sort extension --dir-first"

[[mgr.keymap]]
desc = "Sort by extension (reverse)"
on = [",", "E"]
run = "sort extension --reverse --dir-first"

[[mgr.keymap]]
desc = "Sort alphabetically"
on = [",", "a"]
run = "sort alphabetical --dir-first"

[[mgr.keymap]]
desc = "Sort alphabetically (reverse)"
on = [",", "A"]
run = "sort alphabetical --reverse --dir-first"

[[mgr.keymap]]
desc = "Sort naturally"
on = [",", "n"]
run = "sort natural --dir-first"

[[mgr.keymap]]
desc = "Sort naturally (reverse)"
on = [",", "N"]
run = "sort natural --reverse --dir-first"

[[mgr.keymap]]
desc = "Sort by size"
on = [",", "s"]
run = "sort size --dir-first"

[[mgr.keymap]]
desc = "Sort by size (reverse)"
on = [",", "S"]
run = "sort size --reverse --dir-first"

[[mgr.keymap]]
desc = "Create a new tab using the current path"
on = ["t"]
run = "tab_create --current"

[[mgr.keymap]]
desc = "Switch to the first tab"
on = ["1"]
run = "tab_switch 0"

[[mgr.keymap]]
desc = "Switch to the second tab"
on = ["2"]
run = "tab_switch 1"

[[mgr.keymap]]
desc = "Switch to the third tab"
on = ["3"]
run = "tab_switch 2"

[[mgr.keymap]]
desc = "Switch to the fourth tab"
on = ["4"]
run = "tab_switch 3"

[[mgr.keymap]]
desc = "Switch to the fifth tab"
on = ["5"]
run = "tab_switch 4"

[[mgr.keymap]]
desc = "Switch to the sixth tab"
on = ["6"]
run = "tab_switch 5"

[[mgr.keymap]]
desc = "Switch to the seventh tab"
on = ["7"]
run = "tab_switch 6"

[[mgr.keymap]]
desc = "Switch to the eighth tab"
on = ["8"]
run = "tab_switch 7"

[[mgr.keymap]]
desc = "Switch to the ninth tab"
on = ["9"]
run = "tab_switch 8"

[[mgr.keymap]]
desc = "Switch to the previous tab"
on = ["["]
run = "tab_switch -1 --relative"

[[mgr.keymap]]
desc = "Switch to the next tab"
on = ["]"]
run = "tab_switch 1 --relative"

[[mgr.keymap]]
desc = "Swap the current tab with the previous tab"
on = ["{"]
run = "tab_swap -1"

[[mgr.keymap]]
desc = "Swap the current tab with the next tab"
on = ["}"]
run = "tab_swap 1"

[[mgr.keymap]]
desc = "Show the tasks manager"
on = ["w"]
run = "tasks_show"

[[mgr.keymap]]
desc = "Go to the home directory"
on = ["g", "h"]
run = "cd ~"

[[mgr.keymap]]
desc = "Go to the config directory"
on = ["g", "c"]
run = "cd ~/.config"

[[mgr.keymap]]
desc = "Go to the desktop directory"
on = ["g", "d"]
run = "cd ~/Desktop"

[[mgr.keymap]]
desc = "Go to a directory interactively"
on = ["g", "<Space>"]
run = "cd --interactive"

[[mgr.keymap]]
desc = "Open help"
on = ["~"]
run = "help"

[[select.keymap]]
desc = "Cancel selection"
on = ["<C-q>"]
run = "close"

[[select.keymap]]
desc = "Cancel selection"
on = ["<Esc>"]
run = "close"

[[select.keymap]]
desc = "Submit the selection"
on = ["<Enter>"]
run = "close --submit"

[[select.keymap]]
desc = "Move cursor up"
on = ["k"]
run = "arrow -1"

[[select.keymap]]
desc = "Move cursor down"
on = ["j"]
run = "arrow 1"

[[select.keymap]]
desc = "Move cursor up 5 lines"
on = ["K"]
run = "arrow -5"

[[select.keymap]]
desc = "Move cursor down 5 lines"
on = ["J"]
run = "arrow 5"

[[select.keymap]]
desc = "Move cursor up"
on = ["<Up>"]
run = "arrow -1"

[[select.keymap]]
desc = "Move cursor down"
on = ["<Down>"]
run = "arrow 1"

[[select.keymap]]
desc = "Move cursor up 5 lines"
on = ["<S-Up>"]
run = "arrow -5"

[[select.keymap]]
desc = "Move cursor down 5 lines"
on = ["<S-Down>"]
run = "arrow 5"

[[select.keymap]]
desc = "Open help"
on = ["~"]
run = "help"

[[tasks.keymap]]
desc = "Hide the task manager"
on = ["<Esc>"]
run = "close"

[[tasks.keymap]]
desc = "Hide the task manager"
on = ["<C-q>"]
run = "close"

[[tasks.keymap]]
desc = "Hide the task manager"
on = ["w"]
run = "close"

[[tasks.keymap]]
desc = "Move cursor up"
on = ["k"]
run = "arrow -1"

[[tasks.keymap]]
desc = "Move cursor down"
on = ["j"]
run = "arrow 1"

[[tasks.keymap]]
desc = "Move cursor up"
on = ["<Up>"]
run = "arrow -1"

[[tasks.keymap]]
desc = "Move cursor down"
on = ["<Down>"]
run = "arrow 1"

[[tasks.keymap]]
desc = "Inspect the task"
on = ["<Enter>"]
run = "inspect"

[[tasks.keymap]]
desc = "Cancel the task"
on = ["x"]
run = "cancel"

[[tasks.keymap]]
desc = "Open help"
on = ["~"]
run = "help"
