[[filetype.prepend_rules]]
fg = "#94e2d5"
mime = "image/*"

[[filetype.prepend_rules]]
fg = "#f9e2af"
mime = "video/*"

[[filetype.prepend_rules]]
fg = "#f9e2af"
mime = "audio/*"

[[filetype.prepend_rules]]
fg = "#f5c2e7"
mime = "application/zip"

[[filetype.prepend_rules]]
fg = "#f5c2e7"
mime = "application/gzip"

[[filetype.prepend_rules]]
fg = "#f5c2e7"
mime = "application/x-tar"

[[filetype.prepend_rules]]
fg = "#f5c2e7"
mime = "application/x-bzip"

[[filetype.prepend_rules]]
fg = "#f5c2e7"
mime = "application/x-bzip2"

[[filetype.prepend_rules]]
fg = "#f5c2e7"
mime = "application/x-7z-compressed"

[[filetype.prepend_rules]]
fg = "#f5c2e7"
mime = "application/x-rar"

[[filetype.prepend_rules]]
fg = "#cdd6f4"
name = "*"

[[filetype.prepend_rules]]
fg = "#89b4fa"
name = "*/"

[help.desc]
fg = "#928374"

[help.exec]
fg = "#83a598"

[help.footer]
bg = "#a89984"
fg = "#3c3836"

[help.hovered]
bg = "#504945"
bold = true

[help.on]
fg = "#fe8019"

[[icon.append_rules]]
name = ".git/"
text = ""

[[icon.append_rules]]
name = "Desktop/"
text = ""

[[icon.append_rules]]
name = "Documents/"
text = ""

[[icon.append_rules]]
name = "Downloads/"
text = ""

[[icon.append_rules]]
name = "Dotfiles/"
text = ""

[[icon.append_rules]]
name = "Dropbox/"
text = ""

[[icon.append_rules]]
name = "Music/"
text = ""

[[icon.append_rules]]
name = "Pictures/"
text = ""

[[icon.append_rules]]
name = "Public/"
text = ""

[[icon.append_rules]]
name = "Templates/"
text = ""

[[icon.append_rules]]
name = "Videos/"
text = ""

[[icon.append_rules]]
name = ".bash_aliases"
text = ""

[[icon.append_rules]]
name = ".bash_history"
text = ""

[[icon.append_rules]]
name = ".bash_logout"
text = ""

[[icon.append_rules]]
name = ".bash_profile"
text = ""

[[icon.append_rules]]
name = ".bashprofile"
text = ""

[[icon.append_rules]]
name = ".bashrc"
text = ""

[[icon.append_rules]]
name = ".dmrc"
text = ""

[[icon.append_rules]]
name = ".DS_Store"
text = ""

[[icon.append_rules]]
name = ".fasd"
text = ""

[[icon.append_rules]]
name = ".fehbg"
text = ""

[[icon.append_rules]]
name = ".gitattributes"
text = ""

[[icon.append_rules]]
name = ".gitconfig"
text = ""

[[icon.append_rules]]
name = ".gitignore"
text = ""

[[icon.append_rules]]
name = ".gitlab-ci.yml"
text = ""

[[icon.append_rules]]
name = ".gvimrc"
text = ""

[[icon.append_rules]]
name = ".inputrc"
text = ""

[[icon.append_rules]]
name = ".jack-settings"
text = ""

[[icon.append_rules]]
name = ".mime.types"
text = ""

[[icon.append_rules]]
name = ".ncmpcpp"
text = ""

[[icon.append_rules]]
name = ".nvidia-settings-rc"
text = ""

[[icon.append_rules]]
name = ".pam_environment"
text = ""

[[icon.append_rules]]
name = ".profile"
text = ""

[[icon.append_rules]]
name = ".recently-used"
text = ""

[[icon.append_rules]]
name = ".selected_editor"
text = ""

[[icon.append_rules]]
name = ".vim"
text = ""

[[icon.append_rules]]
name = ".viminfo"
text = ""

[[icon.append_rules]]
name = ".vimrc"
text = ""

[[icon.append_rules]]
name = ".Xauthority"
text = ""

[[icon.append_rules]]
name = ".Xdefaults"
text = ""

[[icon.append_rules]]
name = ".xinitrc"
text = ""

[[icon.append_rules]]
name = ".xinputrc"
text = ""

[[icon.append_rules]]
name = ".Xresources"
text = ""

[[icon.append_rules]]
name = ".zshrc"
text = ""

[[icon.append_rules]]
name = "_gvimrc"
text = ""

[[icon.append_rules]]
name = "_vimrc"
text = ""

[[icon.append_rules]]
name = "a.out"
text = ""

[[icon.append_rules]]
name = "authorized_keys"
text = ""

[[icon.append_rules]]
name = "bspwmrc"
text = ""

[[icon.append_rules]]
name = "cmakelists.txt"
text = ""

[[icon.append_rules]]
name = "config"
text = ""

[[icon.append_rules]]
name = "config.ac"
text = ""

[[icon.append_rules]]
name = "config.m4"
text = ""

[[icon.append_rules]]
name = "config.mk"
text = ""

[[icon.append_rules]]
name = "config.ru"
text = ""

[[icon.append_rules]]
name = "configure"
text = ""

[[icon.append_rules]]
name = "docker-compose.yml"
text = ""

[[icon.append_rules]]
name = "dockerfile"
text = ""

[[icon.append_rules]]
name = "Dockerfile"
text = ""

[[icon.append_rules]]
name = "dropbox"
text = ""

[[icon.append_rules]]
name = "exact-match-case-sensitive-1.txt"
text = "X1"

[[icon.append_rules]]
name = "exact-match-case-sensitive-2"
text = "X2"

[[icon.append_rules]]
name = "favicon.ico"
text = ""

[[icon.append_rules]]
name = "gemfile"
text = ""

[[icon.append_rules]]
name = "gruntfile.coffee"
text = ""

[[icon.append_rules]]
name = "gruntfile.js"
text = ""

[[icon.append_rules]]
name = "gruntfile.ls"
text = ""

[[icon.append_rules]]
name = "gulpfile.coffee"
text = ""

[[icon.append_rules]]
name = "gulpfile.js"
text = ""

[[icon.append_rules]]
name = "gulpfile.ls"
text = ""

[[icon.append_rules]]
name = "ini"
text = ""

[[icon.append_rules]]
name = "known_hosts"
text = ""

[[icon.append_rules]]
name = "ledger"
text = ""

[[icon.append_rules]]
name = "license"
text = ""

[[icon.append_rules]]
name = "LICENSE"
text = ""

[[icon.append_rules]]
name = "LICENSE.md"
text = ""

[[icon.append_rules]]
name = "LICENSE.txt"
text = ""

[[icon.append_rules]]
name = "Makefile"
text = ""

[[icon.append_rules]]
name = "makefile"
text = ""

[[icon.append_rules]]
name = "Makefile.ac"
text = ""

[[icon.append_rules]]
name = "Makefile.in"
text = ""

[[icon.append_rules]]
name = "mimeapps.list"
text = ""

[[icon.append_rules]]
name = "mix.lock"
text = ""

[[icon.append_rules]]
name = "node_modules"
text = ""

[[icon.append_rules]]
name = "package-lock.json"
text = ""

[[icon.append_rules]]
name = "package.json"
text = ""

[[icon.append_rules]]
name = "playlists"
text = ""

[[icon.append_rules]]
name = "procfile"
text = ""

[[icon.append_rules]]
name = "Rakefile"
text = ""

[[icon.append_rules]]
name = "rakefile"
text = ""

[[icon.append_rules]]
name = "react.jsx"
text = ""

[[icon.append_rules]]
name = "README"
text = ""

[[icon.append_rules]]
name = "README.markdown"
text = ""

[[icon.append_rules]]
name = "README.md"
text = ""

[[icon.append_rules]]
name = "README.rst"
text = ""

[[icon.append_rules]]
name = "README.txt"
text = ""

[[icon.append_rules]]
name = "sxhkdrc"
text = ""

[[icon.append_rules]]
name = "user-dirs.dirs"
text = ""

[[icon.append_rules]]
name = "webpack.config.js"
text = ""

[[icon.append_rules]]
name = "*.3g2"
text = ""

[[icon.append_rules]]
name = "*.3gp"
text = ""

[[icon.append_rules]]
name = "*.7z"
text = ""

[[icon.append_rules]]
name = "*.8svx"
text = ""

[[icon.append_rules]]
name = "*.a"
text = ""

[[icon.append_rules]]
name = "*.aa"
text = ""

[[icon.append_rules]]
name = "*.aac"
text = ""

[[icon.append_rules]]
name = "*.aax"
text = ""

[[icon.append_rules]]
name = "*.ai"
text = ""

[[icon.append_rules]]
name = "*.aiff"
text = ""

[[icon.append_rules]]
name = "*.alac"
text = ""

[[icon.append_rules]]
name = "*.amr"
text = ""

[[icon.append_rules]]
name = "*.amv"
text = ""

[[icon.append_rules]]
name = "*.ape"
text = ""

[[icon.append_rules]]
name = "*.apk"
text = ""

[[icon.append_rules]]
name = "*.asf"
text = ""

[[icon.append_rules]]
name = "*.asm"
text = ""

[[icon.append_rules]]
name = "*.asp"
text = ""

[[icon.append_rules]]
name = "*.au"
text = ""

[[icon.append_rules]]
name = "*.aup"
text = ""

[[icon.append_rules]]
name = "*.avi"
text = ""

[[icon.append_rules]]
name = "*.awb"
text = ""

[[icon.append_rules]]
name = "*.awk"
text = ""

[[icon.append_rules]]
name = "*.bash"
text = ""

[[icon.append_rules]]
name = "*.bat"
text = ""

[[icon.append_rules]]
name = "*.bmp"
text = ""

[[icon.append_rules]]
name = "*.bz2"
text = ""

[[icon.append_rules]]
name = "*.c"
text = ""

[[icon.append_rules]]
name = "*.c++"
text = ""

[[icon.append_rules]]
name = "*.cab"
text = ""

[[icon.append_rules]]
name = "*.cbr"
text = ""

[[icon.append_rules]]
name = "*.cbz"
text = ""

[[icon.append_rules]]
name = "*.cc"
text = ""

[[icon.append_rules]]
name = "*.cda"
text = ""

[[icon.append_rules]]
name = "*.class"
text = ""

[[icon.append_rules]]
name = "*.clj"
text = ""

[[icon.append_rules]]
name = "*.cljc"
text = ""

[[icon.append_rules]]
name = "*.cljs"
text = ""

[[icon.append_rules]]
name = "*.cmake"
text = ""

[[icon.append_rules]]
name = "*.coffee"
text = ""

[[icon.append_rules]]
name = "*.conf"
text = ""

[[icon.append_rules]]
name = "*.cp"
text = ""

[[icon.append_rules]]
name = "*.cpio"
text = ""

[[icon.append_rules]]
name = "*.cpp"
text = ""

[[icon.append_rules]]
name = "*.csh"
text = ""

[[icon.append_rules]]
name = "*.css"
text = ""

[[icon.append_rules]]
name = "*.csv"
text = ""

[[icon.append_rules]]
name = "*.cue"
text = ""

[[icon.append_rules]]
name = "*.cvs"
text = ""

[[icon.append_rules]]
name = "*.cxx"
text = ""

[[icon.append_rules]]
name = "*.d"
text = ""

[[icon.append_rules]]
name = "*.dart"
text = ""

[[icon.append_rules]]
name = "*.db"
text = ""

[[icon.append_rules]]
name = "*.deb"
text = ""

[[icon.append_rules]]
name = "*.diff"
text = ""

[[icon.append_rules]]
name = "*.dll"
text = ""

[[icon.append_rules]]
name = "*.doc"
text = ""

[[icon.append_rules]]
name = "*.docx"
text = ""

[[icon.append_rules]]
name = "*.dss"
text = ""

[[icon.append_rules]]
name = "*.dump"
text = ""

[[icon.append_rules]]
name = "*.dvf"
text = ""

[[icon.append_rules]]
name = "*.edn"
text = ""

[[icon.append_rules]]
name = "*.eex"
text = ""

[[icon.append_rules]]
name = "*.efi"
text = ""

[[icon.append_rules]]
name = "*.ejs"
text = ""

[[icon.append_rules]]
name = "*.elf"
text = ""

[[icon.append_rules]]
name = "*.elm"
text = ""

[[icon.append_rules]]
name = "*.epub"
text = ""

[[icon.append_rules]]
name = "*.erl"
text = ""

[[icon.append_rules]]
name = "*.ex"
text = ""

[[icon.append_rules]]
name = "*.exe"
text = ""

[[icon.append_rules]]
name = "*.exs"
text = ""

[[icon.append_rules]]
name = "*.f//"
text = ""

[[icon.append_rules]]
name = "*.fifo"
text = "|"

[[icon.append_rules]]
name = "*.fish"
text = ""

[[icon.append_rules]]
name = "*.flac"
text = ""

[[icon.append_rules]]
name = "*.flv"
text = ""

[[icon.append_rules]]
name = "*.fs"
text = ""

[[icon.append_rules]]
name = "*.fsi"
text = ""

[[icon.append_rules]]
name = "*.fsscript"
text = ""

[[icon.append_rules]]
name = "*.fsx"
text = ""

[[icon.append_rules]]
name = "*.gem"
text = ""

[[icon.append_rules]]
name = "*.gemspec"
text = ""

[[icon.append_rules]]
name = "*.gif"
text = ""

[[icon.append_rules]]
name = "*.gifv"
text = ""

[[icon.append_rules]]
name = "*.go"
text = ""

[[icon.append_rules]]
name = "*.gsm"
text = ""

[[icon.append_rules]]
name = "*.gz"
text = ""

[[icon.append_rules]]
name = "*.gzip"
text = ""

[[icon.append_rules]]
name = "*.h"
text = ""

[[icon.append_rules]]
name = "*.haml"
text = ""

[[icon.append_rules]]
name = "*.hbs"
text = ""

[[icon.append_rules]]
name = "*.hh"
text = ""

[[icon.append_rules]]
name = "*.hpp"
text = ""

[[icon.append_rules]]
name = "*.hrl"
text = ""

[[icon.append_rules]]
name = "*.hs"
text = ""

[[icon.append_rules]]
name = "*.htaccess"
text = ""

[[icon.append_rules]]
name = "*.htm"
text = ""

[[icon.append_rules]]
name = "*.html"
text = ""

[[icon.append_rules]]
name = "*.htpasswd"
text = ""

[[icon.append_rules]]
name = "*.hxx"
text = ""

[[icon.append_rules]]
name = "*.ico"
text = ""

[[icon.append_rules]]
name = "*.iklax"
text = ""

[[icon.append_rules]]
name = "*.img"
text = ""

[[icon.append_rules]]
name = "*.ini"
text = ""

[[icon.append_rules]]
name = "*.iso"
text = ""

[[icon.append_rules]]
name = "*.ivs"
text = ""

[[icon.append_rules]]
name = "*.jar"
text = ""

[[icon.append_rules]]
name = "*.java"
text = ""

[[icon.append_rules]]
name = "*.jl"
text = ""

[[icon.append_rules]]
name = "*.jpeg"
text = ""

[[icon.append_rules]]
name = "*.jpg"
text = ""

[[icon.append_rules]]
name = "*.js"
text = ""

[[icon.append_rules]]
name = "*.json"
text = ""

[[icon.append_rules]]
name = "*.jsx"
text = ""

[[icon.append_rules]]
name = "*.key"
text = ""

[[icon.append_rules]]
name = "*.ksh"
text = ""

[[icon.append_rules]]
name = "*.leex"
text = ""

[[icon.append_rules]]
name = "*.less"
text = ""

[[icon.append_rules]]
name = "*.lha"
text = ""

[[icon.append_rules]]
name = "*.lhs"
text = ""

[[icon.append_rules]]
name = "*.log"
text = ""

[[icon.append_rules]]
name = "*.lua"
text = ""

[[icon.append_rules]]
name = "*.lzh"
text = ""

[[icon.append_rules]]
name = "*.lzma"
text = ""

[[icon.append_rules]]
name = "*.m4a"
text = ""

[[icon.append_rules]]
name = "*.m4b"
text = ""

[[icon.append_rules]]
name = "*.m4p"
text = ""

[[icon.append_rules]]
name = "*.m4v"
text = ""

[[icon.append_rules]]
name = "*.markdown"
text = ""

[[icon.append_rules]]
name = "*.md"
text = ""

[[icon.append_rules]]
name = "*.mdx"
text = ""

[[icon.append_rules]]
name = "*.mjs"
text = ""

[[icon.append_rules]]
name = "*.mka"
text = ""

[[icon.append_rules]]
name = "*.mkv"
text = ""

[[icon.append_rules]]
name = "*.ml"
text = "λ"

[[icon.append_rules]]
name = "*.mli"
text = "λ"

[[icon.append_rules]]
name = "*.mmf"
text = ""

[[icon.append_rules]]
name = "*.mng"
text = ""

[[icon.append_rules]]
name = "*.mogg"
text = ""

[[icon.append_rules]]
name = "*.mov"
text = ""

[[icon.append_rules]]
name = "*.movpkg"
text = ""

[[icon.append_rules]]
name = "*.mp3"
text = ""

[[icon.append_rules]]
name = "*.mp4"
text = ""

[[icon.append_rules]]
name = "*.mpc"
text = ""

[[icon.append_rules]]
name = "*.mpeg"
text = ""

[[icon.append_rules]]
name = "*.mpg"
text = ""

[[icon.append_rules]]
name = "*.msi"
text = ""

[[icon.append_rules]]
name = "*.msv"
text = ""

[[icon.append_rules]]
name = "*.mustache"
text = ""

[[icon.append_rules]]
name = "*.mxf"
text = ""

[[icon.append_rules]]
name = "*.nix"
text = ""

[[icon.append_rules]]
name = "*.nmf"
text = ""

[[icon.append_rules]]
name = "*.norg"
text = ""

[[icon.append_rules]]
name = "*.o"
text = ""

[[icon.append_rules]]
name = "*.oga"
text = ""

[[icon.append_rules]]
name = "*.ogg"
text = ""

[[icon.append_rules]]
name = "*.opus"
text = ""

[[icon.append_rules]]
name = "*.org"
text = ""

[[icon.append_rules]]
name = "*.pdf"
text = ""

[[icon.append_rules]]
name = "*.php"
text = ""

[[icon.append_rules]]
name = "*.pl"
text = ""

[[icon.append_rules]]
name = "*.pm"
text = ""

[[icon.append_rules]]
name = "*.png"
text = ""

[[icon.append_rules]]
name = "*.pp"
text = ""

[[icon.append_rules]]
name = "*.ppt"
text = ""

[[icon.append_rules]]
name = "*.pptx"
text = ""

[[icon.append_rules]]
name = "*.ps1"
text = ""

[[icon.append_rules]]
name = "*.psb"
text = ""

[[icon.append_rules]]
name = "*.psd"
text = ""

[[icon.append_rules]]
name = "*.pub"
text = ""

[[icon.append_rules]]
name = "*.py"
text = ""

[[icon.append_rules]]
name = "*.pyc"
text = ""

[[icon.append_rules]]
name = "*.pyd"
text = ""

[[icon.append_rules]]
name = "*.pyo"
text = ""

[[icon.append_rules]]
name = "*.ra"
text = ""

[[icon.append_rules]]
name = "*.rake"
text = ""

[[icon.append_rules]]
name = "*.rar"
text = ""

[[icon.append_rules]]
name = "*.rb"
text = ""

[[icon.append_rules]]
name = "*.rc"
text = ""

[[icon.append_rules]]
name = "*.rf64"
text = ""

[[icon.append_rules]]
name = "*.rlib"
text = ""

[[icon.append_rules]]
name = "*.rm"
text = ""

[[icon.append_rules]]
name = "*.rmd"
text = ""

[[icon.append_rules]]
name = "*.rmvb"
text = ""

[[icon.append_rules]]
name = "*.rom"
text = ""

[[icon.append_rules]]
name = "*.rpm"
text = ""

[[icon.append_rules]]
name = "*.rproj"
text = "鉶"

[[icon.append_rules]]
name = "*.rs"
text = ""

[[icon.append_rules]]
name = "*.rss"
text = ""

[[icon.append_rules]]
name = "*.rtf"
text = ""

[[icon.append_rules]]
name = "*.s"
text = ""

[[icon.append_rules]]
name = "*.sass"
text = ""

[[icon.append_rules]]
name = "*.scala"
text = ""

[[icon.append_rules]]
name = "*.scss"
text = ""

[[icon.append_rules]]
name = "*.sh"
text = ""

[[icon.append_rules]]
name = "*.slim"
text = ""

[[icon.append_rules]]
name = "*.sln"
text = ""

[[icon.append_rules]]
name = "*.so"
text = ""

[[icon.append_rules]]
name = "*.sql"
text = ""

[[icon.append_rules]]
name = "*.styl"
text = ""

[[icon.append_rules]]
name = "*.suo"
text = ""

[[icon.append_rules]]
name = "*.svi"
text = ""

[[icon.append_rules]]
name = "*.swift"
text = ""

[[icon.append_rules]]
name = "*.t"
text = ""

[[icon.append_rules]]
name = "*.tar"
text = ""

[[icon.append_rules]]
name = "*.tex"
text = "ﭨ"

[[icon.append_rules]]
name = "*.tgz"
text = ""

[[icon.append_rules]]
name = "*.toml"
text = ""

[[icon.append_rules]]
name = "*.ts"
text = ""

[[icon.append_rules]]
name = "*.tsx"
text = ""

[[icon.append_rules]]
name = "*.tta"
text = ""

[[icon.append_rules]]
name = "*.twig"
text = ""

[[icon.append_rules]]
name = "*.vim"
text = ""

[[icon.append_rules]]
name = "*.vimrc"
text = ""

[[icon.append_rules]]
name = "*.viv"
text = ""

[[icon.append_rules]]
name = "*.vob"
text = ""

[[icon.append_rules]]
name = "*.voc"
text = ""

[[icon.append_rules]]
name = "*.vox"
text = ""

[[icon.append_rules]]
name = "*.wav"
text = ""

[[icon.append_rules]]
name = "*.wasm"
text = ""

[[icon.append_rules]]
name = "*.webm"
text = ""

[[icon.append_rules]]
name = "*.webmanifest"
text = ""

[[icon.append_rules]]
name = "*.webp"
text = ""

[[icon.append_rules]]
name = "*.wma"
text = ""

[[icon.append_rules]]
name = "*.wmv"
text = ""

[[icon.append_rules]]
name = "*.wv"
text = ""

[[icon.append_rules]]
name = "*.xbps"
text = ""

[[icon.append_rules]]
name = "*.xcplayground"
text = ""

[[icon.append_rules]]
name = "*.xhtml"
text = ""

[[icon.append_rules]]
name = "*.xls"
text = ""

[[icon.append_rules]]
name = "*.xlsx"
text = ""

[[icon.append_rules]]
name = "*.xml"
text = ""

[[icon.append_rules]]
name = "*.xul"
text = ""

[[icon.append_rules]]
name = "*.xz"
text = ""

[[icon.append_rules]]
name = "*.yaml"
text = ""

[[icon.append_rules]]
name = "*.yml"
text = ""

[[icon.append_rules]]
name = "*.yuv"
text = ""

[[icon.append_rules]]
name = "*.zip"
text = ""

[[icon.append_rules]]
name = "*.zsh"
text = ""

[[icon.append_rules]]
name = "*"
text = ""

[[icon.append_rules]]
name = "*/"
text = ""

[input.border]
fg = "#bdae93"

[input.selected]
reversed = true

[input.title]

[input.value]

[mgr]
border_symbol = " "
tab_width = 1

[mgr.border_style]
fg = "#665c54"

[mgr.cwd]
fg = "#83a598"

[mgr.find_keyword]
fg = "#b8bb26"
italic = true

[mgr.find_position]
bg = "reset"
fg = "#fe8019"
italic = true

[mgr.hovered]
bg = "#83a598"
fg = "#282828"

[mgr.marker_copied]
bg = "#b8bb26"
fg = "#b8bb26"

[mgr.marker_cut]
bg = "#fb4934"
fg = "#fb4934"

[mgr.marker_selected]
bg = "#b8bb26"
fg = "#b8bb26"

[mgr.preview_hovered]
underline = false

[mgr.tab_active]
bg = "#504945"
fg = "#282828"

[mgr.tab_inactive]
bg = "#3c3836"
fg = "#a89984"

[select.active]
fg = "#fe8019"

[select.border]
fg = "#504945"

[select.inactive]

[status]
separator_close = ""
separator_open = ""

[status.mode_normal]
bg = "#A89984"
bold = true
fg = "#282828"

[status.mode_select]
bg = "#b8bb26"
bold = true
fg = "#282828"

[status.mode_unset]
bg = "#d3869b"
bold = true
fg = "#282828"

[status.permissions_r]
fg = "#b8bb26"

[status.permissions_s]
fg = "#665c54"

[status.permissions_t]
fg = "#504945"

[status.permissions_w]
fg = "#fb4934"

[status.permissions_x]
fg = "#b8bb26"

[status.progress_error]
bg = "#3c3836"
fg = "#fb4934"

[status.progress_label]
bold = true
fg = "#ebdbb2"

[status.progress_normal]
bg = "#3c3836"
fg = "#504945"

[status.separator_style]
bg = "#3c3836"
fg = "#3c3836"

[tasks.border]
fg = "#504945"

[tasks.hovered]
underline = true

[tasks.title]

[which]
separator = "  "

[which.cand]
fg = "#83a598"

[which.desc]
fg = "#fe8019"

[which.mask]
bg = "#3c3836"

[which.rest]
fg = "#928374"

[which.separator_style]
fg = "#504945"
