[mgr]
linemode = "none"
show_hidden = true
show_symlink = true
sort_by = "natural"
sort_dir_first = true
sort_reverse = false
sort_sensitive = true

[[opener.edit]]
block = true
run = "nvim \"$@\""

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"

[[plugin.prepend_previewers]]
mime = "audio/*"
run = "exifaudio"

[preview]
cache_dir = ""
image_filter = "triangle"
image_quality = 80
max_height = 900
max_width = 600
sixel_fraction = 15
tab_size = 2
ueberzug_offset = [0, 0, 0, 0]
ueberzug_scale = 1

